# This is a basic workflow to help you get started with Actions

name: Run Update Paper Links Weekly

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron:  "0 8 * * 1"  #Run At 08:00 on Monday
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches:
#     - main

env:

  GITHUB_USER_NAME: ccmeteorljh
  GITHUB_USER_EMAIL: ccmeteor_reg@126.com
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许 workflow 向仓库 push 提交

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          #architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install arxiv requests pyyaml
          
      - name: Run daily arxiv 
        run: |
          python3 daily_arxiv.py --update_paper_links
          
      - name: Push reco-arxiv-daily link updates
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Github Action: Auto Update Recommendation ArXiv Papers"
          files: README.md docs/reco-arxiv-daily.json docs/reco-arxiv-daily-web.json docs/index.md
          rebase: 'true'
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
